name: 'Update data'

on:
  schedule:
    # Run daily at 04:00 UTC (which converts to 05:00 during CET
    # and 06:00 during CEST).
    - cron: '00 04 * * *'
  workflow_dispatch:

jobs:
  update-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'

      - name: Install dependencies
        run: npm install

      - name: Update data
        run: |
          npm run build
          git config user.name 'Tibia buildings bot'
          git config user.email 'buildings@tibiamaps.io'
          git add data
          date=$(date +'%Y-%m-%d')
          git commit data -m "Update @ date=${date}" || true
          git push
